// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1T9A_JBdk5KasvA3gqiyVHvu6NrSMKdo',
    appId: '1:1047593817633:web:6bd4917c7875fc6f483560',
    messagingSenderId: '1047593817633',
    projectId: 'flutter-firebase-auth-e6acf',
    authDomain: 'flutter-firebase-auth-e6acf.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-e6acf.appspot.com',
    measurementId: 'G-9V3QTKWSCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuHCOMaWuBj5amoKvSD0B0k1UXQxfMx0M',
    appId: '1:1047593817633:android:9c47fc28ca459e61483560',
    messagingSenderId: '1047593817633',
    projectId: 'flutter-firebase-auth-e6acf',
    storageBucket: 'flutter-firebase-auth-e6acf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPb_TrQioFCZNRYFxNE4g51poeZafMRtM',
    appId: '1:1047593817633:ios:3620f72868f3ef60483560',
    messagingSenderId: '1047593817633',
    projectId: 'flutter-firebase-auth-e6acf',
    storageBucket: 'flutter-firebase-auth-e6acf.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPb_TrQioFCZNRYFxNE4g51poeZafMRtM',
    appId: '1:1047593817633:ios:3620f72868f3ef60483560',
    messagingSenderId: '1047593817633',
    projectId: 'flutter-firebase-auth-e6acf',
    storageBucket: 'flutter-firebase-auth-e6acf.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1T9A_JBdk5KasvA3gqiyVHvu6NrSMKdo',
    appId: '1:1047593817633:web:36244a378a1269f4483560',
    messagingSenderId: '1047593817633',
    projectId: 'flutter-firebase-auth-e6acf',
    authDomain: 'flutter-firebase-auth-e6acf.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-e6acf.appspot.com',
    measurementId: 'G-PRTQ8431P3',
  );
}
